### PR TITLE
Added page ID to the popup

### PR DESCRIPTION
**Pull request by BradleyArnott**
Gives you the unique page ID on each given area of a V10 site

### CODE REVIEW

**Review by metacurb — CHANGES_REQUESTED** [review]
Please can you minify the extension.min.css? Thanks!

**Review by metacurb — APPROVED** [review]
Looks good to me! 👍

**Comment by BradleyArnott** [comment]
@BeauAgst  CSS has now been minified. Please Review.

**Comment by metacurb** [comment]
Merged, thanks! 🥇

**Comment by BradleyArnott** [comment]
#4 This has resolved issue

**Pull request merged**
